-- MIGRATION: ADD SOFT DELETE SUPPORT
-- Run this in the Supabase SQL Editor

ALTER TABLE cloud_sales ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_expenses ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_products ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_suppliers ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_categories ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_purchases ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_customers ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE cloud_credits ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;

-- If you have expense categories synced:
-- ALTER TABLE cloud_expense_categories ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
